# Generated by Django 4.2.5 on 2024-03-04 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_ticket_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_solucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tecnico_asig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tecnico'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tiempo_dedicado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
