# Generated by Django 4.2.5 on 2024-03-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_respuesta_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha_respuesta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
